// flow-typed signature: 68e29ba692658c9c0010d90e9acb38d6
// flow-typed version: <<STUB>>/extract-css-chunks-webpack-plugin_v^4.7.4/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'extract-css-chunks-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'extract-css-chunks-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'extract-css-chunks-webpack-plugin/dist/cjs' {
  declare module.exports: any;
}

declare module 'extract-css-chunks-webpack-plugin/dist/CssDependency' {
  declare module.exports: any;
}

declare module 'extract-css-chunks-webpack-plugin/dist/hmr/hotModuleReplacement' {
  declare module.exports: any;
}

declare module 'extract-css-chunks-webpack-plugin/dist' {
  declare module.exports: any;
}

declare module 'extract-css-chunks-webpack-plugin/dist/loader' {
  declare module.exports: any;
}

// Filename aliases
declare module 'extract-css-chunks-webpack-plugin/dist/cjs.js' {
  declare module.exports: $Exports<'extract-css-chunks-webpack-plugin/dist/cjs'>;
}
declare module 'extract-css-chunks-webpack-plugin/dist/CssDependency.js' {
  declare module.exports: $Exports<'extract-css-chunks-webpack-plugin/dist/CssDependency'>;
}
declare module 'extract-css-chunks-webpack-plugin/dist/hmr/hotModuleReplacement.js' {
  declare module.exports: $Exports<'extract-css-chunks-webpack-plugin/dist/hmr/hotModuleReplacement'>;
}
declare module 'extract-css-chunks-webpack-plugin/dist/index' {
  declare module.exports: $Exports<'extract-css-chunks-webpack-plugin/dist'>;
}
declare module 'extract-css-chunks-webpack-plugin/dist/index.js' {
  declare module.exports: $Exports<'extract-css-chunks-webpack-plugin/dist'>;
}
declare module 'extract-css-chunks-webpack-plugin/dist/loader.js' {
  declare module.exports: $Exports<'extract-css-chunks-webpack-plugin/dist/loader'>;
}
